--- 
  - name: create_key_pair
    ec2_key:
     name: osaka_key
     region: "{{ aws_region  }}"
    register: key_result
  
  - name: debug key
    debug: 
      var: key_result

  - name: save osaka_key
    copy:
      content: "{{ key_result.key.private_key }}"
      dest: "/home/ec2-user/environment/ansible/osaka_key.pem"
      mode: 0600
    when: key_result.changed

  - name: create_EC2 
    ec2_instance:
      key_name: osaka_key
      name: osaka_jenkins_ec2
      tags:
        name: osaka_jenkins_ec2
      region: "{{ aws_region }}"
      instance_type: t3.medium
      image_id: ami-0b9bc7dcdbcff394e
      security_group: osaka_SG
      wait: yes
      vpc_subnet_id: "{{ public_subnet_1a.subnet.id }}"
    register: osaka_jenkins_ec2
      
    
    