---

  - name: tickethub_SG
    ec2_group:
      name: tickethub_SG
      description: tickethub security group
      vpc_id: "{{ tickethub_vpc.vpc.id }}"
      region: "{{ aws_region }}"
      rules:
        - proto: tcp
          ports:
          - 80
          - 22
          - 8080
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port 80