---
- name: Copy Jenkins installation script and execute
  copy:
    src: /home/ec2-user/environment/privita/ansible2/jenkins_install.sh
    dest: /home/ubuntu/jenkins_install.sh
    mode: '0755'

- name: Execute the script
  shell: /home/ubuntu/jenkins_install.sh

- name: Start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: true