---
  - name: create_key_pair
    ec2_key:
     name: seoul
     region: "{{ aws_region  }}"
    register: key_result

  - name: debug key
    debug:
      var: key_result

  - name: save seoul_key
    copy:
      content: "{{ key_result.key.private_key }}"
      dest: "/home/ec2-user/environment/privita/ansible2/seoul.pem"
      mode: 0600
    when: key_result.changed

  - name: create_EC2
    ec2_instance:
      key_name: seoul
      name: tickethub_jenkins_ec2
      tags:
        name: tickethub_jenkins_ec2
      region: "{{ aws_region }}"
      instance_type: t3.medium
      image_id: ami-0b9bc7dcdbcff394e
      security_group: tickethub_SG
      wait: yes
      vpc_subnet_id: subnet-0d8ae3f720090af05 #프라이빗 서브넷
    register: tickethub_jenkins_ec2

  - name: debug ec2
    debug:
      var: tickethub_jenkins_ec2